/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tiket_Bioskop;

import javax.swing.ButtonGroup;

/**
 *
 * @author LENOVO
 */
public class Pembelian_Tiket extends javax.swing.JFrame {

    /**
     * Creates new form Pembelian_Tiket
     */
    public Pembelian_Tiket() {
        initComponents();
        this.setTitle("Contoh Aplikasi GUI");
        this.setLocationRelativeTo(this);
        
        ButtonGroup bG = new ButtonGroup();
        bG.add(Reguler);
        bG.add(UltraXD);
        bG.add(Gold);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NoTiket = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Reguler = new javax.swing.JRadioButton();
        UltraXD = new javax.swing.JRadioButton();
        Gold = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        HargaSatuan = new javax.swing.JTextField();
        JumlahBeli = new javax.swing.JTextField();
        Proses = new javax.swing.JButton();
        Hapus = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        TotalBayar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Jumlah Beli");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setText("PENJUALAN TIKET BIOSKOP");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 390, 50));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("No Tiket");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 80, 20));

        NoTiket.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NoTiket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoTiketActionPerformed(evt);
            }
        });
        jPanel1.add(NoTiket, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 420, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Jenis Tiket");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 130, 20));

        Reguler.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Reguler.setText("Reguler");
        Reguler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegulerActionPerformed(evt);
            }
        });
        jPanel1.add(Reguler, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 90, -1));

        UltraXD.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        UltraXD.setText("Ultra XD");
        UltraXD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UltraXDActionPerformed(evt);
            }
        });
        jPanel1.add(UltraXD, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 110, -1));

        Gold.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Gold.setText("Gold");
        Gold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoldActionPerformed(evt);
            }
        });
        jPanel1.add(Gold, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 90, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Harga Satuan");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        HargaSatuan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(HargaSatuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 420, 30));

        JumlahBeli.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(JumlahBeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 420, 30));

        Proses.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Proses.setText("OK");
        Proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProsesActionPerformed(evt);
            }
        });
        jPanel1.add(Proses, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, 60, -1));

        Hapus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Hapus.setText("Hapus");
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });
        jPanel1.add(Hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, 90, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Total Bayar");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 110, -1));

        TotalBayar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TotalBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalBayarActionPerformed(evt);
            }
        });
        jPanel1.add(TotalBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 420, 30));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Jumlah Beli");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NoTiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoTiketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoTiketActionPerformed

    private void GoldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoldActionPerformed
        // TODO add your handling code here:
        HargaSatuan.setText("100000");
    }//GEN-LAST:event_GoldActionPerformed

    private void RegulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegulerActionPerformed
        // TODO add your handling code here:
        HargaSatuan.setText("50000");
    }//GEN-LAST:event_RegulerActionPerformed

    private void UltraXDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UltraXDActionPerformed
        // TODO add your handling code here:
        HargaSatuan.setText("60000");
    }//GEN-LAST:event_UltraXDActionPerformed

    private void ProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProsesActionPerformed
        // TODO add your handling code here:
        int c = Integer.parseInt(HargaSatuan.getText());
        int d = Integer.parseInt(JumlahBeli.getText());
        int hasil = c*d;
        TotalBayar.setText("Rp. " + hasil);
        
    }//GEN-LAST:event_ProsesActionPerformed

    private void HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusActionPerformed
        // TODO add your handling code here:
        NoTiket.setText("");
        JumlahBeli.setText("");
        TotalBayar.setText("");
        HargaSatuan.setText("");
        Reguler.setSelected(false);
        UltraXD.setSelected(false);
        Gold.setSelected(false);
        
    }//GEN-LAST:event_HapusActionPerformed

    private void TotalBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalBayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalBayarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pembelian_Tiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pembelian_Tiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pembelian_Tiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pembelian_Tiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pembelian_Tiket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Gold;
    private javax.swing.JButton Hapus;
    private javax.swing.JTextField HargaSatuan;
    private javax.swing.JTextField JumlahBeli;
    private javax.swing.JTextField NoTiket;
    private javax.swing.JButton Proses;
    private javax.swing.JRadioButton Reguler;
    private javax.swing.JTextField TotalBayar;
    private javax.swing.JRadioButton UltraXD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
